### ISSUE TITLE
Art: Cutscene background

### ISSUE THREAD

**Issue by avelitj12** [Splashy-Inc/splish-splashisson#73]
- [ ] Small version of boat (will need to increase in length every level)
- [x] Smaller ocean still frame for ~50% of screen
- [x] Dock/port that boat pulls up to
- [x] Land with market square/circle and forest

Example 640x360 screen:
![New Piskel-1 png (1)](https://github.com/user-attachments/assets/38408b2c-f30b-44b8-b0a3-9a3a71b0cbe1)

**Comment by ChyRoseBun** [comment]
I need Pixel dimensions for this.
